### ISSUE TITLE
Linked example image missing in documentation

### ISSUE THREAD

**Issue by basseur** [bonndan/nivio#30]
The example image on the documentation page [features](https://nivio.readthedocs.io/en/master/features.html) seems to be missing. Chrome gives a 404 and firefox does not load "due to errors in the file".

![https://raw.githubusercontent.com/bonndan/nivio/master/docs/Landscape_example.png](https://raw.githubusercontent.com/bonndan/nivio/master/docs/Landscape_example.png)

**Comment by basseur** [comment]
Actually, I would remove the link and say "see above", because it points to the same image/address anyway. After that, this issue may be closed.

BTW: I was referring to https://nivio.readthedocs.io. There is no "develop" version and the changes are of course not shown.

**Comment by bonndan** [comment]
readthedocs now builds the develop branch as "latest": https://nivio.readthedocs.io/en/latest/
